// Copies this machine's B.E.N. keys into the phone build.
//
// The phone is a second client of the same accounts, and typing two 39-character
// keys on a touchscreen is how people end up with a key that differs by one
// character and an error they cannot read. Run before building.
//
// The output is written to src/provisioned.ts and is NOT source: it holds live
// credentials, so it is generated, git-ignored, and printed only as counts.
import fs from 'fs';
import os from 'os';
import path from 'path';

const settingsPath = path.join(
  os.homedir(),
  'Library/Application Support/jarvis-live/jarvis-settings.json'
);

let desktop = {};
try {
  desktop = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
} catch (err) {
  console.warn(`[provision] no desktop settings found (${err.message}); building without keys`);
}

const geminiKeys = [...new Set([...(desktop.apiKeys || []), desktop.apiKey].map((k) => (k || '').trim()).filter(Boolean))];
const groqApiKey = (desktop.groqApiKey || '').trim();
const wakeWords = Array.isArray(desktop.wakeWords) && desktop.wakeWords.length
  ? desktop.wakeWords
  : ['hey ben', 'ben'];

const file = `// GENERATED by provision.mjs - do not edit, do not commit.
// Holds live API keys copied from this machine's desktop B.E.N. settings.
export const PROVISIONED = {
  geminiApiKeys: ${JSON.stringify(geminiKeys)},
  groqApiKey: ${JSON.stringify(groqApiKey)},
  wakeWords: ${JSON.stringify(wakeWords)}
};
`;

fs.writeFileSync('src/provisioned.ts', file, 'utf8');
console.log(
  `[provision] ${geminiKeys.length} gemini key(s), groq ${groqApiKey ? 'yes' : 'no'}, ` +
    `${wakeWords.length} wake phrase(s) -> src/provisioned.ts`
);
